package cssupport.hbm.pojo;
// Generated 8 Jul, 2014 4:49:08 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * QueueInput generated by hbm2java
 */
public class QueueInput  implements java.io.Serializable {


     private Integer id;
     private Integer objectId;
     private Integer status;

    public QueueInput() {
    }

    public QueueInput(Integer objectId, Integer status) {
       this.objectId = objectId;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getObjectId() {
        return this.objectId;
    }
    
    public void setObjectId(Integer objectId) {
        this.objectId = objectId;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "QueueInput{" + "id=" + id + ", objectId=" + objectId + ", status=" + status + '}';
    }


}


