package cssupport.hbm.pojo;
// Generated 8 Jul, 2014 4:49:08 PM by Hibernate Tools 3.2.1.GA



/**
 * Urls generated by hbm2java
 */
public class Urls  implements java.io.Serializable {


     private Integer id;
     private String type;
     private String url;
     private String hostName;
     private String ip;
     private Integer port;
     private String servlet;
     private Boolean status;

    public Urls() {
    }

    public Urls(Integer id, String type, String url, String hostName, Integer port, String servlet, Boolean status) {
        this.id = id;
        this.type = type;
        this.url = url;
        this.hostName = hostName;
        this.port = port;
        this.servlet = servlet;
        this.status = status;
    }

    
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getHostName() {
        return this.hostName;
    }
    
    public void setHostName(String hostName) {
        this.hostName = hostName;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public Integer getPort() {
        return this.port;
    }
    
    public void setPort(Integer port) {
        this.port = port;
    }
    public String getServlet() {
        return this.servlet;
    }
    
    public void setServlet(String servlet) {
        this.servlet = servlet;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public String toString() {
        return "Urls{" + "id=" + id + ", type=" + type + ", url=" + url + ", hostName=" + hostName + ", ip=" + ip + ", port=" + port + ", servlet=" + servlet + ", status=" + status + '}';
    }

    

}


